### ISSUE TITLE
No muestra las bloqueadas

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#101]
Al iniciar en maganer, muestra la cantidad total de cuentas (6665), y bloqueadas (0), siendo que tenemos en este minuto 43 cuentas bloqueadas.

![captura de pantalla 2016-05-24 a las 7 58 26 p m](https://cloud.githubusercontent.com/assets/5879391/15523672/77937a4c-21f2-11e6-8a25-85e5f9ca3713.png)

**Comment by pbruna** [comment]
@johuder33 hay que corregir el valor de las bloqueadas, esta en `lockedout` y **debe ser** `lockout`.

![captura de pantalla 2016-05-25 a las 6 05 51 p m](https://cloud.githubusercontent.com/assets/352283/15557837/ff9aba90-22ab-11e6-8768-efe8d0c03106.png)

**Comment by pbruna** [comment]
ya funciona.
