### ISSUE TITLE
No busca por status de casilla

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#102]
Al buscar por cualquiera de los status de casilla no muestra nada:

(activa, bloqueada, cerrada, inactiva)

![captura de pantalla 2016-05-24 a las 8 00 16 p m](https://cloud.githubusercontent.com/assets/5879391/15523692/95691d92-21f2-11e6-9ba5-268be3bf6607.png)

**Comment by johuder33** [comment]
este issue esta solventado

**Comment by pbruna** [comment]
Ahora funciona, lo cerrramos.
