### ISSUE TITLE
MX Record

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#103]
En todos los dominios dice: No pudimos obtener el registro MX.

Si aún no está esto hecho, mejor dejarlo en blanco, o no mostrar mensaje, pues va a conducir al cliente a que piense que hay un problema.

![captura de pantalla 2016-05-24 a las 8 02 07 p m](https://cloud.githubusercontent.com/assets/5879391/15523738/e9aeba24-21f2-11e6-9df4-7fb4dc56f39f.png)

**Comment by pbruna** [comment]
Funcionando @deugenin 
![captura de pantalla 2016-05-25 a las 5 33 27 p m](https://cloud.githubusercontent.com/assets/352283/15557026/d22b4320-229e-11e6-82ee-53de5bee69c3.png)
