### ISSUE TITLE
No muestra las casillas usadas

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#104]
Al ver la información del dominio, muestra los límites, pero no la cantidad de casillas usadas por cada clase de servicio. (Están en cero todos).

![captura de pantalla 2016-05-24 a las 8 05 36 p m](https://cloud.githubusercontent.com/assets/5879391/15523790/68ba7740-21f3-11e6-8b08-87bd34259de4.png)

**Comment by johuder33** [comment]
@pbruna el problema que ocurre aqui es que los dominios deberian tener este attr zimbraDomainCOSMaxAccounts, si ese attr existe se executa esta funcion : Domain.maxAccountsByCos(), esa funcion me retorna los limites que existen para cada COS, entonces el problema aqui es que cuando se ejecuta Domain.maxAccountsByCos(), retorna null porque el attr : zimbraDomainCOSMaxAccounts, no esta en el dominio
![captura de pantalla 2016-05-25 a las 10 47 44 a m](https://cloud.githubusercontent.com/assets/12078950/15544327/9f7dfef2-226e-11e6-9e96-fd2f83990b83.png)

**Comment by johuder33** [comment]
ya esta solventado, en la proxima version a produccion se veran los cambios. @deugenin
