### ISSUE TITLE
No exporta los miembros de la lista de distribución

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#105]
Al apretar el boton "Exportar" los miembros de una lista de distribución, no hace nada (Chrome)

![captura de pantalla 2016-05-24 a las 8 09 01 p m](https://cloud.githubusercontent.com/assets/5879391/15523869/e087a28e-21f3-11e6-89fa-d18fea4b9e20.png)

**Comment by johuder33** [comment]
issue solventado

**Comment by pbruna** [comment]
👍
