### ISSUE TITLE
No reconoce las cuentas tipo archiving

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#106]
Al listar las cuentas, para las archiving, muestra "Desconocido"

![captura de pantalla 2016-05-24 a las 8 14 47 p m](https://cloud.githubusercontent.com/assets/5879391/15523961/abb6a194-21f4-11e6-9023-6c74d1a09b0f.png)

**Comment by johuder33** [comment]
@deugenin esta funcionalidad aun no esta lista, ya casi jeje.

**Comment by pbruna** [comment]
@deugenin ya esta listoco.
![captura de pantalla 2016-05-30 a las 3 23 21 p m](https://cloud.githubusercontent.com/assets/352283/15657123/100eadc2-267c-11e6-8a27-81d3745914c2.png)
