### ISSUE TITLE
Muestra factura en borrador

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#107]
Al ver la info de una empresa, muestra las facturas, pero si una tiene alguna en borrador, muestra una línea en blanco, y con el valor como pendiente... no debería mostrarse facturas en borrador.

![captura de pantalla 2016-05-24 a las 8 17 52 p m](https://cloud.githubusercontent.com/assets/5879391/15524013/1e2f9730-21f5-11e6-9002-7700ec4574d1.png)

**Comment by johuder33** [comment]
@pbruna no si debo manejarlo en el front con un attrs en especifico, o lo manejas directo en el backend.

**Comment by pbruna** [comment]
Corregido, y ahora el número es un link a descargar la el PDF de la factura.
cc @deugenin
