### ISSUE TITLE
Suma de los límites de casillas

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#108]
Sigue mala la suma:

![captura de pantalla 2016-05-24 a las 8 54 53 p m](https://cloud.githubusercontent.com/assets/5879391/15524604/4cf5005a-21fa-11e6-8f4d-abdb7cf966d8.png)

**Comment by johuder33** [comment]
@deugenin solventado este issue ;D en la proxima version que se suba te comento para que lo pruebes de nuevo por favor

**Comment by pbruna** [comment]
Funciona.. cerrado.
