### ISSUE TITLE
problemas al mostrar una empresa

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#111]
Cuando intento acceder a una empresa desde un dominio muestra "pagina no encontrada"
![screen shot 2016-05-25 at 5 44 54 pm](https://cloud.githubusercontent.com/assets/17553424/15557369/ed3543e6-22a8-11e6-8e46-4c4305086e54.png)
![screen shot 2016-05-25 at 5 46 10 pm](https://cloud.githubusercontent.com/assets/17553424/15557378/fd550c8e-22a8-11e6-9111-0ddf53e93013.png)

**Comment by johuder33** [comment]
issue solventado

**Comment by pbruna** [comment]
Sigue sin funcionar, da el mismo error que #120

**Comment by johuder33** [comment]
ya se solvento el error, existia un problema con el retorno de la funcion, no lo estaba tratando como una promise
