### ISSUE TITLE
Mostrar 0 en vez de infinito en la suma de casillas.

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#112]
![captura de pantalla 2016-05-25 a las 6 11 27 p m](https://cloud.githubusercontent.com/assets/352283/15557946/bcac0dc8-22ac-11e6-9945-9fd323df646d.png)

**Comment by pbruna** [comment]
Mejor, según recomendación de @johuder33, si no tiene mejor quitar la fila.

**Comment by johuder33** [comment]
issue solventado

**Comment by pbruna** [comment]
Ya funciona.
