### ISSUE TITLE
Error al "editar" dominio 

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#124]
Con administrador de dominio al editar el dominio no carga la página y entrega el siguiente error por consola.
![screen shot 2016-05-30 at 5 04 40 pm](https://cloud.githubusercontent.com/assets/17553424/15658294/3efbcb46-2691-11e6-80e0-bea0b5245165.png)

**Comment by johuder33** [comment]
este issue ha sido solventado, de hecho el admin de dominio no debe editar el dominio. en la proxima version de manager , estara este cambio. probar y dejar el comenetario por esta via para cerra este issue.

**Comment by pbruna** [comment]
Esta ok. Se cierra
