### ISSUE TITLE
Casillas no muestran TIPO

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#125]
Listado de casillas visualizado con cuenta administrador de dominio no muestra el tipo de casilla.
Google Chrome
![screen shot 2016-05-30 at 5 08 01 pm](https://cloud.githubusercontent.com/assets/17553424/15658337/93b7b6fe-2691-11e6-8b5a-49cf0e6151d4.png)

**Comment by johuder33** [comment]
@DavidZbox este issue no lo he podido reproducir, que pasos seguistes para reproducir este error ?

**Comment by DavidZbox** [comment]
@johuder33 solamente ingrese como admin de dominio pero ahora esta bien, muestra los tipos correctamente , este aparecio ayer.
