### ISSUE TITLE
Error en la paginación del listado de casillas.

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#126]
No funciona el botón última/primera entrega lo siguiente la consola.
Google Chrome
![screen shot 2016-05-30 at 5 11 00 pm](https://cloud.githubusercontent.com/assets/17553424/15658374/1275b57c-2692-11e6-9fe1-5e96b0c729e2.png)

**Comment by johuder33** [comment]
issue solventado, probarlo una vez este arriba la proxima version del manager.

**Comment by DavidZbox** [comment]
@johuder33 quedo funcionando como administrador global y como administrador de dominio
