### ISSUE TITLE
correos con eñe

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#129]
Al agregar en la sección de antispam un correo con eñe, da el siguiente mensaje, y de todas maneras se agregó...

![captura de pantalla 2016-05-30 a las 21 45 16](https://cloud.githubusercontent.com/assets/5879391/15660906/b1a0a0e6-26b8-11e6-84da-54df65931f56.png)

**Comment by pbruna** [comment]
@deugenin según veo estas editando un Dominio de tipo `Alias` y creo que el mensaje de error es porque no se puede modificar un dominio alias.

Voy a cerrar este caso ya que hay que revisar dos cosas separadas diferente al mismo, para lo cual abriré dos tickets:

- los dominios alias deben mostrar que son de este tipo y solo mostrar las pestaña Zona DNS,
- corregir agregar el campo al store de anti spam si el server lo rechazó
