### ISSUE TITLE
se pierde página al ver Zona DNS

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#130]
Al ver la zona DNS de cualquier dominio, se pierde la página (tampoco hay un botón cancelar o volver al final).

![captura de pantalla 2016-05-30 a las 21 50 49](https://cloud.githubusercontent.com/assets/5879391/15660929/063e324e-26b9-11e6-9aae-d2a62f477a1f.png)

**Comment by deugenin** [comment]
Y sobre lo mismo,,, al volver atrás con el browser, se pierde la información anterior...

**Comment by pbruna** [comment]
Se cierra, este es el mismo bug de #131
