### ISSUE TITLE
inicio feo

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#131]
Al ingresar se ve feo todo ese espacio en blanco sólo para indicar "Acciones en ejecución"

![captura de pantalla 2016-05-30 a las 21 53 15](https://cloud.githubusercontent.com/assets/5879391/15660962/6c89b1fe-26b9-11e6-9e3b-65120d525a0e.png)

**Comment by pbruna** [comment]
Esto es tuyo @johuder33

**Comment by johuder33** [comment]
jaja un pequeño error de clases, ya esta resuelto.

**Comment by DavidZbox** [comment]
Si , se encuentra resuelto , he revisado por safari y google chrome con cuentas admin global

**Comment by johuder33** [comment]
@DavidZbox perfecto gracias, entonces se da por resuelto este issue.
