### ISSUE TITLE
agregar solicitud de soporte en manager

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#132]
No es un bug, pero como idea: agregar un botón para llenar el formulario de soporte directamente desde manager,,, sin necesidad de ir a ayuda.zboxapp.com y pinchar en el botón http://ayuda.zboxapp.com/#contactModal

![captura de pantalla 2016-05-30 a las 21 55 33](https://cloud.githubusercontent.com/assets/5879391/15660995/c177de5c-26b9-11e6-9593-bf1042b0b766.png)

**Comment by pbruna** [comment]
@johuder33 como dice @deugenin sería bueno tener este cuadro para pedir soporte.

Nosotros usamos http://www.helpscout.net/ para llevar los tickets de soporte y ellos proveen una herramienta llamada `Beacons` para hacer integraciones. Su uso es sencillo, aquí está la doc y un video de ejemplo: http://developer.helpscout.net/beacons/

Es ideal que el cuadro de dialogo se auto-complete con la siguiente información del usuario que se trae de Zimbra:
* Nombre completo
* Dirección de Correo
* Dominio
* Empresa

Y que el usuario **deba** llenar:
* Asunto,
* Mensaje

Y que _pueda_ subir adjuntos.

**Comment by pbruna** [comment]
Ah @johuder33, @DavidZbox tiene acceso de Admin a HelpScout por cualquier cosa que se necesite hacer.

**Comment by johuder33** [comment]
@pbruna @deugenin esta sugerencia ya esta en produccion.
