### ISSUE TITLE
dominios con eñe

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#133]
Al crear un nuevo dominio, me permitió altiro crear uno con eñe... debería denegarlo altiro,,, o hacer la transformación a formato IDN.

![captura de pantalla 2016-05-30 a las 21 58 00](https://cloud.githubusercontent.com/assets/5879391/15661049/5e446f8e-26ba-11e6-982c-a373c13730ab.png)

**Comment by deugenin** [comment]
Sobre esto mismo, al agregarle un registro, quedó pegado  dando vueltas sin hacer nada al apretar "Guardar",, pero el dominio sí se creó.

**Comment by pbruna** [comment]
@deugenin la fotos que pegas es la creación de un dominio en Zimbra, solo disponible para administradores globales. 

Manager no hace ninguna validación, le pasa los datos al servicio (PowerDNS, Zimbra, Folio o Mailcleaner) y este acepta o rechaza. Entonces en este caso Zimbra si acepta ese dominio.

Tomando lo anterior y dado que solo está disponible a nosotros, administradores globales, pienso que debemos dejarlo así.

Por otro lado hay que ver qué hace PowerDNS con caracteres UTF8

**Comment by johuder33** [comment]
@pbruna @deugenin se agrego un validar en el front end sobre si el dominio tiene algun caracter especial, si es asi retorna un error y lo invitamos a verificar, lo que hace falta probar es el  tema de el powerdns

**Comment by pbruna** [comment]
Voy a cerrar esto y creo otro,
