### ISSUE TITLE
Mejoras Zona DNS

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#134]
Hay que implementar las siguientes mejoras:

- confirmación al borrar registro
- paginación de lista
- búsqueda por nombre o contenido 
- cuadro para agregar registro debe aparecer al principio, no al final

**Comment by johuder33** [comment]
lista confirmacion
lista busqueda
listo cuadro para agregar al principio
falta paginacion.

**Comment by pbruna** [comment]
Veo todo ok.. cerramos.
