### ISSUE TITLE
Corrección a Dominios Alias

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#135]
Ticket relacionado con el #129 reportado por @deugenin 

- la api Zimbra debe incluir una propiedad `isAliasDomain` que retorne `true` o `false`
- Indicar en búsquedas si es un dominio alias
- en las búsquedas no mostrar casillas
- indicar al verlo que es un dominio alias
- al verlo no mostrar cuadro de casillas
- al verlo mostrar cuál es el dominio maestro
- solo mostrar la pestaña zona dns

**Comment by pbruna** [comment]
@johuder33 te paso este Issue.
Por si acaso actualicé la librería y ahora el dominio responde a las siguientes propiedades:

* `domain.isAliasDomain`, `true | false`
* `domain.masterDomainName`, el nombre del dominio padre.

**Comment by johuder33** [comment]
genial :+1:

**Comment by johuder33** [comment]
solventado, por favor testear @pbruna

**Comment by pbruna** [comment]
@johuder33 Este está ok pero abrí otro para hacer una mejora.
