### ISSUE TITLE
El componente anti spam guarda incluso si Zimbra lo rechaza

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#136]
@johuder33 por favor revisa esto que está relacionado con el ticket #129 que reportó @deugenin 

Lo que pasa es que si bien Zimbra rechaza la solicitud, Manager igual lo guarda en el store

**Comment by johuder33** [comment]
este ya esta solventado. revisarlo una vez se suba la version, yo lo avisare via Now

**Comment by DavidZbox** [comment]
Se reviso y manager indica correctamente que no se pueden agregar dominios con 'ñ' y ademas este no guarda la lista .
![screen shot 2016-05-31 at 1 58 47 pm](https://cloud.githubusercontent.com/assets/17553424/15685045/5b5ff262-2740-11e6-976c-baed187e1e76.png)

**Comment by johuder33** [comment]
perfecto issue, entonces procedemos a cerrar el issue.
