### ISSUE TITLE
Error en espacio asignado a la casilla tipo profesional

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#137]
La casilla tipo profesional muestra como limite de espacio **ilimitado**, lo correcto es **50GB**
Google Chrome
![screen shot 2016-05-31 at 9 29 17 am](https://cloud.githubusercontent.com/assets/17553424/15676091/534b3200-271b-11e6-978f-773f35197d3f.png)

**Comment by johuder33** [comment]
este issue ya esta solventado, se podra verificar en la proxima version del manager.

**Comment by DavidZbox** [comment]
@johuder33 ya se ha solventado, no muestra como espacio total **ilimitado** pero tampoco muestra el espacio total de la casilla .

**Comment by pbruna** [comment]
Me lo asigno, parece que es porque no se puede obtener la Cos.

**Comment by pbruna** [comment]
revisar si no es mejor obtener esto desde la info del usuario en vez de la cos

**Comment by pbruna** [comment]
cerrado. veo todo Ok
