### ISSUE TITLE
Al editar casilla te muestra la opción de archiving

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#138]
Al editar una casilla muestra la opción **archiving**, tengo entendido que las casillas de tipo archiving se crean de manera automática cuando una casilla es de tipo **Premium**. No debería 
Google Chrome
![screen shot 2016-05-31 at 9 35 49 am](https://cloud.githubusercontent.com/assets/17553424/15676345/369b38ca-271c-11e6-8a57-4fc51b4a8b51.png)

**Comment by johuder33** [comment]
issue solventado, estara presente en la proxima version de manager.

**Comment by DavidZbox** [comment]
@johuder33 issue solucionado, ya no muestra la opción de Archiving.
