### ISSUE TITLE
Al activar un admin de dominio no muestra un mensaje relacionado con la acción

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#140]
Cuando se activa un administrador de dominio todo funciona correctamente pero no hay un mensaje que indique al usuario que la acción se ha ejecutado.
Google Chrome
![screen shot 2016-05-31 at 10 15 30 am](https://cloud.githubusercontent.com/assets/17553424/15677553/2277b71a-2721-11e6-9c13-b85a04f82bcd.png)

**Comment by pbruna** [comment]
Sobre lo mismo,
Cambiar el botón amarillo a uno Azul o verde, no parece un botón, parece un `label`.

**Comment by johuder33** [comment]
@pbruna ok se cambiara, aunque no se si enviar un mensaje al activar un administrador de dominio, debido a que el mismo se agrega automaticamente en el listado de admins de dominio, entonces, si el se muestra un mensaje estaria fuera del modal, con el MessageBar, y si apenas se active el admin se le cierra el modal, seía incomodo para el usuario pues tal vez pueda seguir agregando otros administradores.
