### ISSUE TITLE
Administrador de dominio puede cambiar dominio de cuentas

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#141]
Como zboxadmin@asoex.cl me permite editar la extension de una casilla , debería darme un listado de los dominios permitidos o asignados al administrador de dominio .
Ejemplo trate de editar la casilla testmanager@asoex.cl y pude cambiar por testmanager@zboxapp.com escribiendo y al momento de guardar me indica un error sobre permisos para asignar clase de servicio a las casillas .
Este error lo solucionaba a través de zboxAdmin agregando el permiso a nivel global y por cos para poder asignar la clase de servicio (profesional, basic, premium) a las casillas .
![screen shot 2016-05-31 at 11 14 59 am](https://cloud.githubusercontent.com/assets/17553424/15679862/d28b4344-2729-11e6-93d1-7b7763722791.png)

**Comment by DavidZbox** [comment]
@pbruna  en este issue quiero aclarar 
1- Estoy usando e este ejemplo la casilla zboxadmin@asoex.cl
2- la casilla como explicaba en el issue se llamaba testmanager@asoex.cl y pude editar su extension a testmanager@**zboxapp.com** , yo sugiero que el campo de dominio debería mostrar un listado con los dominios en los que la casilla zboxadmin@asoex.cl tiene permisos para crear casillas 
3 - Al momento de querer guardar la modificación salto el error que parece en la imagen **permission denied: need right: assignCos for cos Basic** , como te comente hace un tiempo este error aparecio a los administradores en la plataforma de zboxAdmin, este error es a cual me refiero en el issue [#144](https://github.com/ZBoxApp/manager-react/issues/144)

Espero ahora si haya quedado claro, tratare de ser más claro para no generar más confusión .

**Comment by pbruna** [comment]
@DavidZbox este bug no tiene pata ni cabezas.  cerrado
