### ISSUE TITLE
Como administrador de dominio no muestra estadisticas de casillas

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#143]
Como zboxadmin@asoex.cl no muestra las estadisticas al editar ver la información de una casilla
Google Chrome
![screen shot 2016-05-31 at 11 26 31 am](https://cloud.githubusercontent.com/assets/17553424/15680435/28c99560-272c-11e6-9b09-1e9cb08ae91e.png)

**Comment by pbruna** [comment]
@DavidZbox tu ya sabes ya.. la imagen por si sola no sirve de mucho. Pega el error que te da la consola.

**Comment by DavidZbox** [comment]
@pbruna apenas pueda recrear el problema agregare la información . no he podido recrear la información por este issue que acabo de generar [#150](https://github.com/ZBoxApp/manager-react/issues/150)
