### ISSUE TITLE
No se puede crear casillas con administrador de dominio

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#144]
No se puede crear casillas porque faltan los permisos para asignar clases de servicio al administrador de dominio .
Ejemplo de la asignación de permiso en zboxAdmin
![screen shot 2016-05-31 at 12 11 35 pm](https://cloud.githubusercontent.com/assets/17553424/15681858/68c49282-2731-11e6-94d7-d2e96322ce7f.png)

También se puede asignar este permiso de la siguiente manera
![screen shot 2016-05-31 at 12 13 51 pm](https://cloud.githubusercontent.com/assets/17553424/15681903/93a29ac6-2731-11e6-8665-b1c99ba08f88.png)

**Comment by pbruna** [comment]
Resuelto en #153
