### ISSUE TITLE
callback success en zonaDNS.createOrModifyRecords, no retorna el objecto con la api

### ISSUE THREAD

**Issue by johuder33** [ZBoxApp/manager-react#152]
Cuando se obtiene el zoneDNS, se obtiene un objecto de constructor Zone, este constructor tiene la api para permitir request de este tipo zonedns.request() ...

el issue esta que powerdns no devuelve el mismo constructor de Zone, y es alli donde no se puede crear o modificar registros de una Zona DNS, adjunto screenshot que indica el error y un track que informa como se pierde el contructor en la llamada.
![captura de pantalla 2016-06-01 a las 6 21 52 p m](https://cloud.githubusercontent.com/assets/12078950/15727638/5b961150-282e-11e6-9a23-59a7894ba3d5.png)

**Comment by johuder33** [comment]
@pbruna este error un persiste, pero lo solvente haciendo nuevamente el llamado de l zonaDNS, osea por ahora esta asi, pero deberiamos solventarlo desde al api sin hacer llamadas extras a la API PowerDNS.

**Comment by johuder33** [comment]
@pbruna se podra podrar en la proxima version

**Comment by pbruna** [comment]
@johuder33 ya está resuelto por mi lado. La API ya funciona ok.
