### ISSUE TITLE
Problema Cache, para poder asignar permisos a los admins delegados.

### ISSUE THREAD

**Issue by johuder33** [ZBoxApp/manager-react#153]
El problema esta que cuando se asigna un admin delegado para que este pueda crear casillas bajo su dominio, bien sea casillas con planes de : Basic, Professional o Premium, al admin delegado no puede crearla debido a que necesita permisos para crear casillas con esas caracteristica.

**Comment by pbruna** [comment]
Ya está solucionado, por favor revisar

**Comment by pbruna** [comment]
Ya está corregido
