### ISSUE TITLE
Algunos registros DNS no se deben modificar.

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#154]
@deugenin que registros no deben modificarse? Y qué valores deben tener por defecto?

**Comment by deugenin** [comment]
@pbruna : 
- SOA
- NS
- MX
- TXT (del SPF)  <- pero aquí puede haber más adicionales modificables por el admin

Por los valores por defecto, no hay una fijo para todos por igual, esos valores se crean con uno template, pero que es modificable dependiendo del cliente.

**Comment by pbruna** [comment]
@johuder33 tuve que agregar lo siguiente a la config para corregir esto:
```
"dns": {
        "url": "https://manager.zboxapp.com/powerdns_proxy/",
        "token": "otto",
        "inmutable": ["mx", "soa", "ns", "spf"] // <---- Nuevo
    },
```

**Comment by pbruna** [comment]
@deugenin por favor puedes revisar que esto funcione correctamente y si está Ok cierras el caso.
Gracias.

**Comment by pbruna** [comment]
Bueno @deugenin si encuentras el error de nuevo reabres el caso

**Comment by pbruna** [comment]
@johuder33 con la última actualización este bug volvió a aparecer, yo lo había resuelto con el branch `zonedns_reserver_records`, el que acabo de recuperar. Por favor dale una vuelta

**Comment by johuder33** [comment]
@pbruna este issue se solvento el viernes, disculpa no coloque le comentario aqui.
