### ISSUE TITLE
No se puede asignar administrador de dominio

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#156]
Como administrador global david@zboxapp.com no puedo agregar administrador a los dominios .
Google Chrome
![screen shot 2016-06-06 at 9 35 26 am](https://cloud.githubusercontent.com/assets/17553424/15823829/c5ef57c6-2bd2-11e6-9abe-3c8eb852d4f1.png)

**Comment by pbruna** [comment]
@DavidZbox puedes vaciar tu cache y probar de nuevo. A mí me funcionó, prueba con otro domain admin

**Comment by DavidZbox** [comment]
@pbruna realice lo que pediste y tampoco funciono , esta vez probe con otro dominio, el error fue el mismo.

**Comment by DavidZbox** [comment]
@pbruna ahora esta funcionando , cierro el issue.

**Comment by johuder33** [comment]
@DavidZbox @pbruna algo extraño sucede, con el dominio zarth se hizo la prueba y si ciertamente funcionó, pero con el dominio de prueba de zboxtest, creé una casilla llamda johutest@zboxtest.com e intenté asignarla como admin y me da error 500, el mismo error de siempre.


![issue](https://cloud.githubusercontent.com/assets/12078950/15826523/39856062-2bde-11e6-9343-2893697c23bb.png)

**Comment by pbruna** [comment]
@johuder33 tienes que vaciar absolutamente todos los caches y cookies y refrescar con CMD+R.

Es un problema de sesiones y cache de cookies.
