### ISSUE TITLE
Tarea masiva "Mensaje fuera de oficina"

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#158]
Como administrador de dominio al realizar tarea masiva "Mensaje fuera de oficina" indica que se realiza el proceso sin problemas pero no se ha realizado la acción .
Revise a través de zimbraAdmin y manager y el mensaje no fue configurado en las casillas,

**Comment by johuder33** [comment]
@DavidZbox issue solventado, no se estaban pasando las fechas formateadas por eso no realizaba la actividad. en el proximo PR se veran los cambios reflejados

**Comment by DavidZbox** [comment]
Listo @johuder33 revisado y funcionando
