### ISSUE TITLE
Eliminar registro en DNS no muestra error.

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#161]
Como administrador de dominio cuando se intenta eliminar un registro no se realiza la acción .
Esto es correcto, un administrador de dominio no puede borrar registros en la pestaña de zona DNS pero tampoco se muestra un mensaje que indique que la acción no puede ser realizada .
Además el recuadro que pide la confirmación para la eliminación queda en pantalla y no se puede quitar después de confirmar la acción.
Google Chrome
![screen shot 2016-06-06 at 1 05 59 pm](https://cloud.githubusercontent.com/assets/17553424/15830637/f32b3ef4-2bef-11e6-9f68-2d21a3366fd1.png)

**Comment by pbruna** [comment]
@DavidZbox ojo que los Administradores de Dominio si deben poder modificar sus Zonas DNS.

**Comment by johuder33** [comment]
Se verifico, y se produce un error al momento de borrar una registro DNS, se adjunta los screenshots.
@pbruna no se si esto es problema del router que maneja Nginx. porque en mis pruebas locales todo funciona bien.

![captura de pantalla 2016-06-06 a las 3 32 09 p m](https://cloud.githubusercontent.com/assets/12078950/15834976/54f015d8-2c04-11e6-8f6a-455d11ff2765.png)
![captura de pantalla 2016-06-06 a las 3 32 29 p m](https://cloud.githubusercontent.com/assets/12078950/15834975/54eb0d54-2c04-11e6-8b0e-5d0ea543eb38.png)

**Comment by pbruna** [comment]
@johuder33 parece que es error en mi lado y relacionado con #167 
Lo veo hoy

**Comment by pbruna** [comment]
El problema era una configuración en NGINX. Ya esta resuelto.
