### ISSUE TITLE
BatchRequest no retorna la respuesta de forma correcta.

### ISSUE THREAD

**Issue by johuder33** [ZBoxApp/manager-react#162]
El batchrequest que se usa para retorna la respuesta de mensaje vacaciones masivo, no retorna las cuentas afectadas con el formato necesitado, es decir retorna las cuentas afectadas con sus attrs encapsulados en un arreglo y no un objeto, entonces luego de un mensaje masivo se deben actualizar en el store todas las cuentas afectadas, y por ahora se dificulta la actualizacion del store debido a que el formato de retorno del batch request no es igual a como si se estuviera realizando un getAccount o getAlllAccount, por favor retorna la respuesta del batchjrequest como si se estuviera realizando un getAccount.

![captura de pantalla 2016-06-06 a las 1 18 09 p m](https://cloud.githubusercontent.com/assets/12078950/15831133/6d29d5d8-2bf2-11e6-9f6c-4987f514bece.png)

**Comment by pbruna** [comment]
@johuder33 consulta: esto es necesario ahora que siempre estamos consultando a Zimbra?

**Comment by pbruna** [comment]
Lo acabo de probar y funciona Ok.
Lo voy a cerrar por ahora y lo abrimos una vez que comencemos a trabajar en el nuevo manejo de Stores.
