### ISSUE TITLE
No refresca la página al eliminar un administrador de dominio

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#165]
Al momento de eliminar un administrador de dominio en la configuración de un dominio, la página no refresca y no muestra si este fue eliminado o no.
Google Chrome.

**Comment by johuder33** [comment]
Ciertamente no muestr que el admin ha sido eliminado o no, verificando la consola el error viene del api zimbra, al parecer no existe una variable llamada coses.

![captura de pantalla 2016-06-06 a las 3 02 12 p m](https://cloud.githubusercontent.com/assets/12078950/15834231/c373fd16-2c00-11e6-956d-7318354de3fb.png)

**Comment by pbruna** [comment]
@johuder33 mi error, se me olvidó avisarte que ahora también es necesario pasar los nombres de las `coses` a `removeAdmin()`:

```javascript
const coses = ['default', 'test', 'professional'];
domain.addAdmin(account.id, coses, callback);
// {} if Success

domain.removeAdmin(account.id, coses, callback);
// {} if Success
```

**Comment by johuder33** [comment]
perfecto, se podrá probar en la proxima version.

**Comment by pbruna** [comment]
funcionando Ok. se cierra.
