### ISSUE TITLE
Todos los dominios aparecen en estado "Migrando"

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#168]
Como administrador global todos los dominios se muestran en migración y como administrador de dominio también muestra en estado migrando al dominio.

Google Chrome
![screen shot 2016-06-06 at 3 47 52 pm](https://cloud.githubusercontent.com/assets/17553424/15836045/5096428c-2c09-11e6-8021-6bfa435a7953.png)

**Comment by johuder33** [comment]
@DavidZbox este issue no se logra reproducir, se verificará mañana.

**Comment by DavidZbox** [comment]
@johuder33 he revisado y ya no aparece como tal.

**Comment by pbruna** [comment]
@DavidZbox si esta ok, por favor cerrar el caso

**Comment by johuder33** [comment]
@DavidZbox cuando ocurra, reabres este issue, y me llamas para verlo directo en tu maquina.
