### ISSUE TITLE
No mostrar Dominios Alias en /domains

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#171]
@johuder33 creo que es mejor que si el Dominio el Alias, este no se muestre cuando se pincha el link Dominios y te lleva a `/domains`. Es confuso verlo ahí y también que muestre `0 casillas`

**Comment by johuder33** [comment]
ya esta, se podrá ver en la próxima versión.

**Comment by pbruna** [comment]
revisado y esta ok.
