### ISSUE TITLE
Al acceder a un dominio no aparece el administrador de dominio

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#172]
He asignado un administrador al dominio andestecnologia.cl, cuando accedo nuevamente al dominio no aparece el administrador que acabo de configurar.

Imágenes al momento de acceder al dominio.
![screen shot 2016-06-07 at 11 33 21 am](https://cloud.githubusercontent.com/assets/17553424/15864147/44b491b4-2cac-11e6-8832-5c826bcf8fef.png)
![screen shot 2016-06-07 at 11 33 33 am](https://cloud.githubusercontent.com/assets/17553424/15864151/4860f618-2cac-11e6-9172-786c3cb0fdac.png)

Cuando refresco la página aparece el administrador y también los límites de las casillas para el dominio que tampoco se mostraban
![screen shot 2016-06-07 at 11 34 00 am](https://cloud.githubusercontent.com/assets/17553424/15864173/5e1a9928-2cac-11e6-96cc-4c3d10fa01eb.png)

**Comment by pbruna** [comment]
probado y ahora funciona ok.
