### ISSUE TITLE
Siempre refrescar recurso

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#173]
@johuder33 creo que por el momento es mejor que siempre hagamos la solicitud a Zimbra en vez de leer el Store, ya que hay varios _bugs_ que se están repitiendo y parece que tienen que ver con datos almacenados en el Store.

Una vez que estén corregidos esos bugs, probamos nuevamente el cache del store, si es que vale la pena, quizás Zimbra responda lo suficientemente rápido por si sólo.

**Comment by johuder33** [comment]
ya esta en produccion este punto.

**Comment by pbruna** [comment]
si, funciona bien. cerramos
