### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#176]
@DavidZbox es necesario que de aquí al Lunes 13, mi _regreso_ esté lista la documentación en http://ayuda.zboxapp.com como lo conversamos. Los puntos que deben estar cubierto son:

### Admin. de Dominios
* Agregar Administradores,
* AntiSpam
* Listas de Distribución: Crear, Editar, miembros, restricciones
* Tareas masivas
* Administración de Zona DNS
* Ver casillas y exportar listado

### Casillas
* Filtro por Estado,
* Filtro por Plan,
* Nueva Casilla,
* Importa y Exportar
* Ver casilla y que significa la info
* Cambio de contraseña,
* Borrado de Casilla,
* Ver correos
* Respuesta de vacaciones
* Alias

### Mi Empresa
* Info de Dominios
* Info de Facturas y estado 
* Descarga de Factura al presionar el link del número

### Búsqueda Global
* Mostrar que retorna de todo y de forma rápida

### Solicitud de Soporte
* Explicar como funciona el link y cuadro para pedir soporte desde Manager, una vez que esté listo.

**Comment by DavidZbox** [comment]
@pbruna enlace de la documentación [Doc ZBox Manager](http://ayuda.zboxapp.com/collection/125-zbox-manager)

Solo faltan dos puntos

- Solicitud de soporte 
- Administración de Zona DNS
