### ISSUE TITLE
Zona DNS no crea los registros.

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#178]
Intento crear los registros en la pestaña Zona DNS en el dominio consultoraproactiva.com pero no se guarda los datos ingresados.
intente con un solo registro y con varios a la vez pero el resultado es el mismo.
![screen shot 2016-06-07 at 5 47 52 pm](https://cloud.githubusercontent.com/assets/17553424/15875888/a10cd80c-2ce0-11e6-9de2-e465bafe8b4c.png)

**Comment by johuder33** [comment]
@DavidZbox @pbruna esto se debe a que , cuando se busca la zona dns del dominio, la respuesta que nos da la api es un objecto instancia de un objecto, osea cuando le damos un console.log a la respuesta de la consulta, esta, nos retorna un Object {}, y no un ZoneDNS {}, es alli donde falla las demas consulta porque lo que retorna no es un objecto ZonaDNS, sino un objecto puro de javascript y no la instancia de ZonaDNS

**Comment by pbruna** [comment]
@johuder33 esto es mi culpa, cierto?

**Comment by johuder33** [comment]
@pbruna jaja si hay que reviar porque no devuelve el objecto que contiene la api

**Comment by johuder33** [comment]
@pbruna acabo de ver que el error es mio jajaj, el error es causado porque faltaba esto
" * as Client "
el problema es que no estaba importando todas las funciones del Client Zimbra jaja :(

**Comment by johuder33** [comment]
este issue esta solventado. se podrá probar en la próxima versión

**Comment by pbruna** [comment]
También había un problema en NGINX que ya está resuelto.
