### ISSUE TITLE
Después de eliminar una casilla no se retorna al listado del dominio

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#182]
Estoy eliminando casillas de zboxapp.com
Accedo al dominio -> ver casillas -> eliminar x casilla,  después de eliminar la casilla el navegador vuelve a la sección de casillas pero el general no a la sección de casillas de zboxapp.com

**Comment by pbruna** [comment]
@DavidZbox asigna el ticket y coloca si es un bug o no.
También escribiste dos cosas, la idea es que cada Issue solo tenga que ver con una cosas, si quieres avisar de dos cosas abres 2 Issues por favor.

**Comment by DavidZbox** [comment]
@pbruna creo que no tengo la capacidad de asignar el issue y de asignar un label .
te adjunto imagen 
![screen shot 2016-06-08 at 3 14 39 pm](https://cloud.githubusercontent.com/assets/17553424/15907582/238326ac-2d94-11e6-8661-9313f52af607.png)

**Comment by johuder33** [comment]
este issue, ha sido solventado, estara en el proximo release.

**Comment by pbruna** [comment]
esta ok
