### ISSUE TITLE
Lista de Distribucion: Buscardor en Permitidos no funciona

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#184]
Al buscar, no funciona.
<img width="860" alt="captura de pantalla 2016-06-08 a las 2 39 20 p m" src="https://cloud.githubusercontent.com/assets/352283/15906445/e2b27ed2-2d86-11e6-8d80-9ce10cf13934.png">

El error de la consola es:
```
Uncaught TypeError: Cannot read property 'match' of undefined
panel_actions_allows.jsx?1f36:84 
```

**Comment by pbruna** [comment]
@johuder33 acabo de hacer una prueba que si funciona con una lista nueva: https://manager.zboxapp.com/domains/38458361-f422-41e7-ad1f-d78dbca74fd4/distribution_lists/866557b1-5dad-4256-9d81-597fb6faec22

Con la lista del ejemplo anterior no funciona porque hay un elemento en blanco
<img width="670" alt="captura de pantalla 2016-06-08 a las 2 47 55 p m" src="https://cloud.githubusercontent.com/assets/352283/15906712/0e82f626-2d88-11e6-92d2-39a25cb64d47.png">

El link de la lista es: https://manager.zboxapp.com/domains/6bae72c2-b509-4f98-b298-219ade7e91e6/distribution_lists/d983a932-88e3-49fd-8be2-e00a3be38acd

**Comment by johuder33** [comment]
@pbruna esto se debe a que esa lista que aparece en blanco no tiene nombre, y cuando comienzas a escribir cuando se intenta hacer el regex, da error porque no se puede buscar un patron en un element undefined, eso da porque verificamos y ese permitido no tiene nombre y por eso da el error, lo que hice fue que si no tiene nombre colocamos el id, y le asignamos un error para que el usuario sepa que existe un error en esa lista. en la proxima version que subiré lo prodra ver.

**Comment by pbruna** [comment]
@johuder33 sería posible pegar una alerta si pasa eso? Porque es un error en Zimbra y deberíamos corregirlo

**Comment by johuder33** [comment]
si la alerta ya existe, y esta el produccion @pbruna

**Comment by pbruna** [comment]
esta ok 👍
