### ISSUE TITLE
Busqueda Global: Link de Lista de Distribución no funciona

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#185]
Cuando se busca una lista en el buscador global, el link no funciona porque está tratando de ir a la lista dentro de un dominio y no hay dominio, el link al que trata de ir es, por ejemplo si busco `privada@zboxtest.com`, el link es:

```
https://manager.zboxapp.com/domains/null/distribution_lists/866557b1-5dad-4256-9d81-597fb6faec22
```

Si te fijas en `/domains/null/` el null es lo que nos está dando problemas.

**Comment by johuder33** [comment]
este issue ha sido solventado. :D

**Comment by johuder33** [comment]
verificar en la produccion.

**Comment by pbruna** [comment]
esta ok 👍
