### ISSUE TITLE
Mostrar limites de casillas en la creación de casillas

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#187]
Lo ideal es que el usuario pueda ver cuantas casillas quedan disponibles para la creación y por tipo como muestra zimbra Admin
![screen shot 2016-06-08 at 6 29 25 pm](https://cloud.githubusercontent.com/assets/17553424/15913560/19e32b8e-2db1-11e6-81c6-1e21f4d4982a.png)
@johuder33

**Comment by johuder33** [comment]
esta mejora ha sido implementada se puede verificar apenas petete anuncie que manager ha sido actualizado.

**Comment by pbruna** [comment]
@johuder33 creo que sería mejor mostrar la cantidad bajo la selección. Algo así:
<img width="992" alt="captura de pantalla 2016-06-13 a las 6 30 01 a m" src="https://cloud.githubusercontent.com/assets/352283/16004568/b212374e-3138-11e6-9828-044d3b426730.png">

**Comment by pbruna** [comment]
listo 👍
