### ISSUE TITLE
retornar el elemento que se creo cuando se agregan permitidos en lista de distribucion.

### ISSUE THREAD

**Issue by johuder33** [ZBoxApp/manager-react#188]
@pbruna es posible que cuando se agrega un permitido en una lista de distribucion, si todo esta ok, la respuesta me retorne el elemento creado con su nombre, id , y type, tal como si lo estuviera solicitando a la api ?? porque actualmente no lo retorna, seria genial que lo retornara.
![captura de pantalla 2016-06-08 a las 7 09 14 p m](https://cloud.githubusercontent.com/assets/12078950/15914223/68e75b02-2db5-11e6-8ef4-faad5f7cefa9.png)

**Comment by pbruna** [comment]
@johuder33 ahora estamos entregando la lista modificada. Asi que cierro este caso
