### ISSUE TITLE
Administradores de Dominio no deben ver el boton para agregar otro Admin de Dominio

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#192]

**Comment by johuder33** [comment]
@pbruna el admin de dominio, puede editar o eliminar otros admin de dominio , o tambien les quito esos botones ?

**Comment by johuder33** [comment]
@pbruna se soluciona este issue, se quitan todas las acciones si no es admin global, estara en la proxima version.

**Comment by pbruna** [comment]
está ok
