### ISSUE TITLE
No se puede agregar permitidos a la lista de distribución como administrador de dominio

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#193]
Cuando se intenta agregar un usuario permitido para una lista de distribución entrega el siguiente error : 

**Hubo un error al agregar david@zboxapp.com, debido a : permission denied: insufficient right to grant 'sendToDistList' right**

**Comment by DavidZbox** [comment]
@johuder33 por favor.

**Comment by DavidZbox** [comment]
@johuder33 aquí la captura.
El usuario administrador global es administrador@zboxtest.com 

![screen shot 2016-06-09 at 4 17 54 pm](https://cloud.githubusercontent.com/assets/17553424/15948407/06510afc-2e77-11e6-8038-6b4a81629923.png)

**Comment by pbruna** [comment]
Tiene que ver con los permisos de Zimbra

**Comment by pbruna** [comment]
Tiene que ver con el #194

**Comment by pbruna** [comment]
@johuder33 ya se pueden agregar, pero no refresca cuando se agrega, esto es porque ahora la api devuelve la lista actualizada.
