### ISSUE TITLE
No se recargan las listas de distribución

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#201]
Lo mismo que el #200 pero con las listas.

**Comment by johuder33** [comment]
@pbruna con que probaste este issue ? porque me funciona todo bien sin modificacion alguna jeje

**Comment by johuder33** [comment]
@pbruna estoy viendolo, es extraño porque a veces funciona a veces no. pero local no sucede

**Comment by johuder33** [comment]
@pbruna ya lo solvente, en realida todo esta bien, pero al parecer el evento que se dispara es mas rapido que la actualizacion en zimbra, lo extraño es que cuando zimbra retorna el callback se supone que ya actualizó los datos, pero realmente no, entonces el proceso es este 

1. Se agrega / elimina
2. se espera respuesta del request bien sea si agregó o eliminó.
3. cuando zimbra da respuesta y dice que todo esta OK, entonces se emite un evento que actualiza las DL.
4 cuando ese evento se ejecutada hacer un Domain.getAllDistributionLists(callback), cuando esto se ejecuta no existe la lista que se agregó o eliminó, entonces el evento resulta ser mas rapido que la actualización de zimbra.

la solución ? simplemente coloqué un delay para volver a refresca.

**Comment by pbruna** [comment]
@johuder33 parece que hay que poner más delay, porque a veces funciona y a veces no.

**Comment by pbruna** [comment]
estamos ok 👍
