### ISSUE TITLE
Esconder funciones

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#202]
Debido a algunos problemas de permisos en Zimbra que deben ser resueltos es necesario ocultar las siguientes funciones a los administradores de dominio:

* Seccion AntiSpam
* Usuarios permitidos en la lista de Distribución.

**Comment by johuder33** [comment]
@pbruna resuelto, disponible proxima release.

**Comment by pbruna** [comment]
@johuder33 aun se ve la pestaña permitidos.
![captura de pantalla 2016-06-13 a las 12 27 16 p m](https://cloud.githubusercontent.com/assets/352283/16015104/920036f4-316a-11e6-8d35-1fb1c67e6589.png)

**Comment by pbruna** [comment]
estamos Ok 👍
