### ISSUE TITLE
El plan debería indicar si se debe habilitar archiving

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#211]
La configuración de los planes debería indicar si luego de crear una casilla o cambiar el plan de una casilla se debe crear su casilla archiving:

```
...
"Premium": {
            "statusCos": "btn-primary2",
            "label": "Premium",
            "isEnabledToEdit": true,
            "archiving": true,
            "forRights": true
        },
...
```

Si el plan tiene configurado `archiving === true` entonces se debe habilitar el archiving llamando a la función `account.enableArchiving(callback)`.

Esto se debe hacer cuando:
* Se crea una nueva casilla,
* La casilla se cambia de Plan

**Comment by johuder33** [comment]
@pbruna esto es siempre y cuando se cree o cambie a Premium cierto ?

**Comment by pbruna** [comment]
@johuder33 como conversamos, depende de la configuración del plan.

**Comment by pbruna** [comment]
esta Ok
