### ISSUE TITLE
Zona DNS modifica los valores cuando el registro tiene el mismo nombre

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#226]
En la pestaña de zona DNS al momento de agregar un registro con el mismo **nombre** que otro registro pero con **distinto contenido** el registro no se agrega si no que **modifica el que ya existe**.
 @johuder33

**Comment by DavidZbox** [comment]
@pbruna con la actualización se ha solventado este issue pero aún tiene un error.
Realice dos pruebas : 
- Agregue un registro A para el dominio zboxtest.com con el nombre `pato.zboxtest.com` con el contenido `104.236.112.189` y este valor se agrego correctamente.
![screen shot 2016-06-23 at 9 10 23 am](https://cloud.githubusercontent.com/assets/17553424/16304193/bef6d02e-392a-11e6-80d1-fec9aea605a4.png)
 - Intente agregar otro registro TXT con el nombre `zboxtest.com` con el valor `"v=spf1 include:_spf.zboxapp.com -all"` y el mensaje que entrega la plataforma es que se ha agregado correctamente pero no se muestra entre los registros , tampoco entrega un error la consola .
El registro TXT que ya existe con el nombre zboxtest.com tiene como contenido `"v=spf1 include:_spf.zboxapp.com ~all"`

**Comment by pbruna** [comment]
Pero,
Se borro el que existía?



Saludos. 

----------------------------------------
Patricio Bruna
CEO - IT Linux 
(+56-2) 2902 3001
(+56-9) 8899 6618
www.itlinux.cl / blog.itlinux.cl

Correo enviado a través de
ZBox: Correo y Colaboración en la Nube

**Comment by DavidZbox** [comment]
No , no se borra el registro TXT.
Pero no se agrega el nuevo .

**Comment by pbruna** [comment]
@DavidZbox lo que pasa es que la app no está dejando modificar o agregar nada que tenga como nombre sólo el dominio, estoy viendo porque.

**Comment by pbruna** [comment]
@DavidZbox corregido
