### ISSUE TITLE
Empresa que no debería aparecer

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#232]
Encontré la empresa Forus, que no tiene ni casillas ni dominios en Zimbra. No debería aparecer.

![captura de pantalla 2016-06-28 a las 18 54 03](https://cloud.githubusercontent.com/assets/5879391/16435167/53f76b32-3d6a-11e6-9c1f-bd8eb9407582.png)

**Comment by pbruna** [comment]
@deugenin, aparecen todas las empresas existentes en el Folio de ZBox, Forus es una de ellas por el backup, así que por eso aparece.

Solo nosotros los Admin Full vemos todas las empresas, y los Admin de dominio ven su empresa.

De Forus no pueden ingresar porque no tienen usuarios Admin.

Así que no es tema que se muestren todas las empresas.
