### ISSUE TITLE
Información por defecto de cuota de correos

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#233]
Si el dominio no tiene configurada esta preferencia, debería mostrar el valor por defecto del zimbraMtaMaxSize que tenemos configurado. Muestra ahora 1 MB y confunde al cliente que piensa que actualmente tiene 1 MB de cuota de tráfico por correo. Debería mostrar el valor actual, y la opción de subir/bajar.

![captura de pantalla 2016-06-28 a las 19 00 03](https://cloud.githubusercontent.com/assets/5879391/16435303/551ab40a-3d6b-11e6-9386-9f2026c3b310.png)

**Comment by johuder33** [comment]
@deugenin esta solventado, podra verse en la próxima versión
