### ISSUE TITLE
no se puede renombrar casillas

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#235]
Como administrador global al momento de **renombrar** una casilla Manager entrega el siguiente error.

![screen shot 2016-06-30 at 11 40 40 am](https://cloud.githubusercontent.com/assets/17553424/16494655/785fee0c-3ec0-11e6-805d-9c0b847da838.png)

No entrega errores por consola, solamente el mensaje que aparece en la captura 
@johuder33

**Comment by pbruna** [comment]
comprobado, es un problema de React que seguramente no encuentra la instancia de la casilla

**Comment by johuder33** [comment]
@DavidZbox etse issue esta solventado, visible en la próxima versión
