### ISSUE TITLE
Indicar botón para cerrar sesión 

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#238]
Un cliente indico que no encontraba el botón para cerrar sesión 
[no puedo cerrar sesión](https://secure.helpscout.net/conversation/218593961/2687/?folderId=647181)

Sería bueno colocar un botón o texto que dijera "cerrar sesión" para evitar esto.

**Comment by DavidZbox** [comment]
@johuder33

**Comment by johuder33** [comment]
@DavidZbox issue solventado accesible en la próxima version

**Comment by DavidZbox** [comment]
solventado y se cierra.
