### ISSUE TITLE
Dominios sin casillas no muestran limites de casillas asignadas al dominio

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#247]
Cuando un dominio no tiene casillas creadas no muestra los límites asignados al dominio.
@johuder33

**Comment by johuder33** [comment]
@DavidZbox este issue esta solventado, por favor verificar y cerrar.

**Comment by DavidZbox** [comment]
Si se ha solventado 
Se cerra issue

Saludos
