### ISSUE TITLE
Información de la casilla no muestra DL a las que pertenece la casilla.

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#262]
Al entrar a la información de una casilla no se muestra a las listas de distribución que pertenece la casilla.
![screen shot 2016-07-20 at 11 02 57 am](https://cloud.githubusercontent.com/assets/17553424/16991448/9d870f2c-4e69-11e6-8d10-a47ac2a13d41.png)

@johuder33

**Comment by johuder33** [comment]
este issue fue solventado.
