### ISSUE TITLE
Poder administrar los reenvíos de las casillas

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#263]
Actualmente en la información de una casilla no se puede configurar los reenvíos y los reenvíos ocultos de correos recibidos.
Esta funcionalidad es bastante utilizada por los administradores de dominio.
@johuder33

**Comment by johuder33** [comment]
@DavidZbox esta mejora, ya esta en producción por favor pruebala y si todo esta bien cierra este issue por favor.

**Comment by DavidZbox** [comment]
@johuder33 documentando ahora .
Gracias, saludos.
