### ISSUE TITLE
Configurar atributo zimbraPrefPop3DownloadSince desde Manager

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#273]
Este atributo de las **casillas** permite indicar desde que fecha se comenzará a descargar los correos cuando se accede a la casilla a través de **POP**

La fecha de este atributo viene en formato UTC 
Ejemplo de una casilla configurada para que su descarga sea desde el 22 de Agosto del 2016
```
DavidGatica@MacBook-Pro-de-David:~/www/zbprov/zbprov/lib|accounts⚡
⇒  node index.js ga cgonzalez@international-line.cl | grep zimbraPrefPop3DownloadSince
     zimbraPrefPop3DownloadSince: '20160822030000Z',
DavidGatica@MacBook-Pro-de-David:~/www/zbprov/zbprov/lib|accounts⚡
```

Existen varias solicitudes por parte de international-line.cl respecto a la modificación de este atributo.
@johuder33

**Comment by pbruna** [comment]
Esto no va.
No se aceptan nuevas funciones para la versión de Manager actual, sólo corrección de errores.
