### ISSUE TITLE
Falta de ortografía

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#276]
- Al borrar una casilla:   "dese" -> "desea"

Borrar Casilla

¿Esta seguro que dese borrar la casilla .......?

**Comment by johuder33** [comment]
este iissue fue solventado en el [branch](https://github.com/ZBoxApp/manager-react/blob/fix-mistake-word-remove-modal/src/components/mailbox/edit_mailbox.jsx#L245)
