### ISSUE TITLE
Mostrar DL a las que pertenece una casilla

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#278]
En la administración anterior de zimbra, la información de una casilla se puede visualizar las DL a las que pertenece la casilla.
![screen shot 2016-09-02 at 12 36 15 pm](https://cloud.githubusercontent.com/assets/17553424/18209408/fe8d5c96-7109-11e6-9c39-9dc016e34d40.png)
Esto es necesario ya que varios administradores de dominio han solicitado que en ZBox Manager se pueda visualizar también esta información.
@johuder33

**Comment by johuder33** [comment]
este issue fue solventado en el [branch](https://github.com/ZBoxApp/manager-react/blob/add-dl-user-belongs-to/src/components/mailbox/mailbox_details.jsx#L120)
