### ISSUE TITLE
Se necesita poder quitar permisos en ZBox Manager

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#281]
Un cliente solicita poder quitar el permiso para "Ver correos" de las casillas a un administrador de dominio en ZBox Manager (solicitud que otros clientes me han mencionado ).
Se quitaron los permisos : 
- loginAs
- adminLoginAs

A la casilla de administración pero la casilla aún puede utilizar esta función de "Ver correos" desde ZBox Manager.

**Comment by johuder33** [comment]
Este issue fue resulto en el [branch](https://github.com/ZBoxApp/manager-react/blob/show-see-mails-button-based-grants/src/components/mailbox/mailbox_details.jsx#L125).
