### ISSUE TITLE
Problema al eliminar casillas de forma individual.

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#283]
Bug reportado por uno de nuestros clientes.

"Al momento de presionar el botón para confirmar la eliminación de una casilla, dicho botón presionado aparece con tres puntos blancos, los cuales nunca dejan de aparecer ..."

![image](https://cloud.githubusercontent.com/assets/17553424/20190939/31583482-a762-11e6-954a-445c8c6d1069.png)

- Pese a que la vista no desaparece de la pantalla la casilla si es eliminada .
@johuder33

**Comment by johuder33** [comment]
este issue ya fue solventado en el [branch](https://github.com/ZBoxApp/manager-react/blob/remove-account-correctly/src/components/mailbox/edit_mailbox.jsx#L301), ahora se pasa a background el remove account y cuando la cuenta se borre de forma total el sistema avisará enviando una notificación.
