### ISSUE TITLE
Limitar acceso a menu Empresas

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#59]
Si el usuario es Administrador de Dominio y no Administrador Global, el Link `Empresas` debería ser reemplazado por uno que se llame `Mi Empresa` y que le muestre sólo su empresa.

**Comment by pbruna** [comment]
@johuder33 si bien muestra "Mi Empresa"  el link aun llama a `companies`

**Comment by johuder33** [comment]
@pbruna se ha subido una solución para este issue

**Comment by pbruna** [comment]
@johuder33 No funciona, al presionar el link "Mi Empresa" lleva a `/companies` y no a `/companies/{id}`

**Comment by pbruna** [comment]
Esta relacionado con #111
