### ISSUE TITLE
Botón exportar casillas no hace nada

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#70]
Al listar las casillas de un dominio, al presionar el botón "exportar" no hace nada...

![captura de pantalla 2016-05-18 a las 9 43 36 p m](https://cloud.githubusercontent.com/assets/5879391/15380150/0eaf7b7c-1d4a-11e6-9954-a01678b7ed54.png)

**Comment by DavidZbox** [comment]
Se debe importar

- email: **name**
- nombre: **givenName** y **sn**
- Tipo: **zimbraCOSId**
- estado: **zimbraAccountStatus**

**Comment by johuder33** [comment]
issue solventado

**Comment by pbruna** [comment]
Ya funciona.
