### ISSUE TITLE
Bloqueo de propia cuenta 

### ISSUE THREAD

**Issue by deugenin** [ZBoxApp/manager-react#71]
Me quise hacer un candado chino, y bloquié mi propia cuenta de admin. Pero la página queda visualizando así. (debería cerrar la sesión)
En Chrome.

![captura de pantalla 2016-05-18 a las 10 16 24 p m](https://cloud.githubusercontent.com/assets/5879391/15380664/ccf93326-1d4e-11e6-8a2b-948eadf99a0d.png)

**Comment by johuder33** [comment]
este issue esta solventado, ahora simplemente te lleva a login y arroja el error de que el token expiró
