### ISSUE TITLE
Facturas deben mostrar Total formateado

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#85]
El campo Total de la tabla debería estar formateado, por ejemplo `53763 -> $ 53.763`
Ahora se muestran así:

![captura de pantalla 2016-05-21 a las 12 31 37 p m](https://cloud.githubusercontent.com/assets/352283/15449602/395752d4-1f50-11e6-8755-8b3f384886ab.png)

**Comment by johuder33** [comment]
solved, se debe verificar @pbruna

**Comment by johuder33** [comment]
solved
