### ISSUE TITLE
Dominios Alias y Archive deberían ser ignorados en las búsquedas

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/manager-react#88]
Si un dominio es del tipo `alias`, los que tienen el atributo: `zimbraDomainType: alias`, al visitarlo sólo debería mostrar los cuadros:

* Información general, y aquí indicar que es un dominio `Alias`, y un link al Dominio maestro.

Como el siguiente ejemplo:
![captura de pantalla 2016-05-22 a las 8 12 31 a m](https://cloud.githubusercontent.com/assets/352283/15453902/01c04aba-1ff5-11e6-82bf-e4b85e48efaf.png)

**Comment by pbruna** [comment]
@johuder33 cierro este porque todo está en #135

**Comment by johuder33** [comment]
solventado de igual manera
